- index.html
ICO and STO copy added, believe issue can be closed
> ICO and STO copy added

- css/icomoon.css
icon colours added to icon scss
> icon colour changed made to icon.scss

- index.html
Added github address for contact section
> Added github address

- index.html
mail address corrected, linkedin page added, created as target=blank …to maintain consistency
> Issue 25 completed

- index.html
> Added Open Collective logo

- index.html
It's not particularly clear what the correct formatting is so just check that you're happy with it.
Closes #51
> Added traditional place name to address

- index.html
> Chore:  Change to h2 to make style more consistant.

- index.html
> Chore: Update to new office

- clients.html
LODA & Handle links added under client
> added clients

- index.html
> Fix what3words 

- careers.html
- clients.html
- css/style.css
- sass/style.scss
- themesh.html
- venture-studio.html
This covers
headers consistency 
Mesh page bugs
holacracy principals added
> Web consistency #88 #87 #65

- index.html
Moved social links to the bottom of the page to match other pages.
> move social links

- about.html
- careers.html
- css/style.css
- index.html
- services.html
- trial-day.html
- venture-studio.html
added blog link and image to site
> added blog

- the/mesh.html
Added ENS for Barry Earsman `earsman.eth`
> Add ENS for Barry

- the/mesh.html
> Added-Jasmin-ENS

- the/mesh.html
Signed-off-by: TomDodson <91101134+TomDodson@users.noreply.github.com>
> Add me to the mesh!

- clients.html
> Updated PowerPlay link

- css/style.css
- sass/style.scss
- fix glitchy animation
- it should now fade in correctly
Note: 
- scss and css file is out of sync with css contain newer change, so css is manually edit and not transpile from scss in this PR
> Fix animation

- the/mesh.html
> cooper's ens

- index.html
- Added link to IPFS version of website
> feat: add IPFS link
